### ISSUE TITLE
Question about colgen with CPLEX

### ISSUE THREAD

**Issue by lucasfernog** [pcbouman-eur/JavaCplexExample#2]
Does CPLEX determines which column should be removed from the basis? Because you don't explicitly do that.

**Comment by pcbouman-eur** [comment]
In general these examples use CPLEX as an LP solver, and if it uses the simplex method (there are other options such as the barrier method) then maybe it does, but probably it does something more sophisticated than standard simplex. Basically, in these models the LP solver is more or less considered a black box.
